# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComprasDiscosUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 394)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_correo = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_correo.setObjectName("lineEdit_correo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_correo)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_dir = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dir)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_tel = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_tel)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_nom = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_nom.setObjectName("lineEdit_nom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nom)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(200, 10, 221, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 69, 47, 16))
        self.label_6.setObjectName("label_6")
        self.spinBoxCant = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxCant.setGeometry(QtCore.QRect(63, 69, 51, 20))
        self.spinBoxCant.setObjectName("spinBoxCant")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 23, 201, 40))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBoxDiscos = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxDiscos.setObjectName("comboBoxDiscos")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxDiscos)
        self.pushButtonComprar = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonComprar.setGeometry(QtCore.QRect(60, 100, 75, 23))
        self.pushButtonComprar.setObjectName("pushButtonComprar")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(10, 160, 411, 221))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Datos del cliente"))
        self.label_2.setText(_translate("Form", "Correo:"))
        self.label_3.setText(_translate("Form", "Dirección:"))
        self.label_4.setText(_translate("Form", "Telefono:"))
        self.label.setText(_translate("Form", "Nombre:"))
        self.groupBox_2.setTitle(_translate("Form", "Compra"))
        self.label_6.setText(_translate("Form", "Cantidad:"))
        self.label_5.setText(_translate("Form", "Disco:"))
        self.pushButtonComprar.setText(_translate("Form", "Comprar"))
